### ISSUE TITLE
headerShrink down when scrolling down in any view scroll position

### ISSUE THREAD

**Issue by gastonbesada** [ionic-team/ionic-ion-header-shrink#1]
Hi @mlynch Could you extend the headerShrink to work when scroll down. I tried to make this change but I fail.

If you see in Facebook iOS app, headerShrink works this way. The header bar can be shrinking down in any view scroll position. 

Also, could you extend to use it in subheader-bar and nav-bar?

Thanks and regards

**Comment by gastonbesada** [comment]
Hi @mlynch, Is here the best place to follow this issue?
Thanks

**Comment by mlynch** [comment]
@gastonbesada take a look, just added this in master!
