### ISSUE TITLE
Graphical issues with ion-side-menus

### ISSUE THREAD

**Issue by nickcmaynard** [ionic-team/ionic-ion-header-shrink#3]
When used with ion-side-menus, the header does not shrink correctly.

jsfiddle to show the issue: http://jsfiddle.net/9ntrhd8y/1/

**Comment by agustinhaller** [comment]
The same happens to me.
I think it's because of the cached ion-header-bar when you have multiple pages.
This query selector in the headerShrink directive must be getting the wrong element and causing that ugly effect.

``` javascript
var header = $document[0].body.querySelector('.bar-header');
```

**Comment by nicowenterodt** [comment]
As a quick fix you can select all headers and iterate over shrinking them all. You also have to fix the automatically added class "has-header".  Just switch the top property with a padding-top.

http://jsfiddle.net/9esgc7np/4/

**Comment by nickcmaynard** [comment]
@Ionitron closed, why?
