### ISSUE TITLE
manage mulitple header-bars when using ion-nav-bar

### ISSUE THREAD

**Issue by nicowenterodt** [ionic-team/ionic-ion-header-shrink#7]
When I use an ion-nav-bar with an nav-view-controller I found out that there are multiple header-bars rendered into the DOM (active, cache, entering etc.) 

![screenshot 2015-02-13 18 59 19](https://cloud.githubusercontent.com/assets/411126/6192469/a605e4f0-b3b2-11e4-939b-2893c184b195.png)

We have to shrink all of them when scrolling down. For now the querySelector selects only the first element matching the ".bar-header" class.

I'm already working on a fork but maybe you guys already got an idea.

**Comment by nickcmaynard** [comment]
Suspect this is related to #3

**Comment by nickcmaynard** [comment]
@Ionitron closed, why?
