### ISSUE TITLE
I tried to add it in my project with side bar templates but I always get error

### ISSUE THREAD

**Issue by shfaizanali** [ionic-team/ionic-ion-header-shrink#9]
I get error on 
e.detail.scrollTop 
it says e.detail is undefined, then I tried something like
if(e.detail){
    scrollTop = e.detail.scrollTop;
}else if(e.target){
    scrollTop = e.target.scrollTop;
}
it always give me scroll top value of 1

I am using the directive in my code by just adding header-shrink directive to content and using with ion-nav-bar

**Comment by NBAMj** [comment]
I'm facing the same issue
